---
title: "Rooftop Solar Research"
author: "Yohan Min"

date: "Updated `r Sys.Date()`"

output:
  bookdown::gitbook:
    config:
      toc:
        collapse: no
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: yes
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
    sharing:
      facebook: yes
      twitter: yes
      google: no
      linkedin: no
    all: ['facebook', 'google', 'twitter', 'linkedin']

---

<!-- Packages -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message=FALSE)
```


# 1. Social Equity in Clean Energy Policies {#index}

## Motivation 
* Energy divide (e.g. Digital divide)
* Clean energy policy
* Social equity

## Observation 

* Mapping clean energy technologies (i.e. PV and EV) 
* Uneven distribution (clustering pattern)

## Hypotheses 

* Uneven distirubtion is related to socio-demographic characteristics 

## Literature review 

* Disscussion on the most significant factors on the clean energy technologies 

## Methods 

* Spatial autocorrelation
* Spatial regression
* Factor analysis (dimension reduction)
* Cluster analysis (grouping)

## Result

* The most significant factors are housing stability, and economic status 

## Discussion 

* Comparison with other papers 
* Uniqueness of this research 
* Shortcomings and future research opportunities 

## Contribution 

* The most significant factors to the uneven distribution were identified
* Spatial autocorrelation were addressed 
* Similar variables were combined by Factor analysis 
* Socio-demographic data from ACS could be used as predictors for other regions
* Sensitive regions were identified 
* Policy maker could refer to this results

# 2. Peneration Model (PV, and EV)

## Motivation 

* Differnt diffusion trend by region
* Temporal increase of variables in trend

## Observation 

* Mapping diffusion of trend of clean energy technologies (i.e. PV and EV) 
* Bass diffusion model (new adopter model)

## Hypotheses 

* A certain policy may affect the diffusion trend different among regions 

## Literature review 

* Diffusion models
* Early adapter characteristics 
* Peer effect 

## Methods 

* Time series analysis
* Event based regression 
* Applying traditional diffussion model 

## Result

* The most significant factor influencing the diffusion trend is the community involvement  

## Discussion 

* Comparison with other papers 
* Uniqueness of this research 
* Shortcomings and future research opportunities 

## Contribution 

* The most significant factor to the diffusion was identified
* Diffusion model were addressed on PV and EV
* New finding on importance of community involvement on diffusion 
* Prediction model was suggested 
* Policy maker could refer to this results to increase PV and EV diffusion while saving the acquisition cost 


# 3. Identifying Regions Vulnerable to Variable Electric Balance 

## Motivation 

* Different diffusion pattern between PV and EV 
* Large amount of variable renewable sources leads to development of storage and demand-side solutions
* Attention should be regions with higher decentralization trend due to the supply-demand balance 
* Differnt diffusion trend by region
* Variable temporal increase in trend

## Observation 

* Mapping EV and PV trend by region

## Hypotheses 

* A certain region needs more attention due to addition of clean energy technologies

## Literature review 

* Impact of higher decentralization trend of PV and EV on Grid operation
* Importance of identifying the regions with higher decentralization trend
* Methods to identify those regions

## Methods 

* Time series analysis
* clustering analysis 
* Simulation 

## Result

* Identifying the most significant regions for independent system operator (ISO) to take attention  

## Discussion 

* Comparison with other papers 
* Uniqueness of this research 
* Shortcomings and future research opportunities 

## Contribution 

* The most significant region was identified
* Prediction model was suggested to estimate the future impact of addtion of PV and EV
* Policy maker and utilities could refer to this results to plan their investment on systems of distribution and scalable renewable energy

# Reference 

* “5 Corporate Renewable Energy Trends to Watch in 2020.” (n.d.). LevelTen Energy.
* Araújo, K., Boucher, J. L., and Aphale, O. (2019). “A clean energy assessment of early adopters in electric vehicle and solar photovoltaic technology: Geospatial, political and socio*demographic trends in New York.” Journal of Cleaner Production, 216, 99–116.
* “As corporate renewable buying surges, innovative PPAs pressure utilities to improve green tariffs.” (n.d.). Utility Dive, <https://www.utilitydive.com/news/> (Feb. 21, 2020).
* Balta-Ozkan, N., Yildirim, J., and Connor, P. M. (2015). “Regional distribution of photovoltaic deployment in the UK and its determinants: A spatial econometric approach.” Energy Economics, 51, 417–429.
* Chan, G., Evans, I., Grimley, M., Ihde, B., and Mazumder, P. (2017). “Design choices and equity implications of community shared solar.” The Electricity Journal, Energy Policy Institute’s Seventh Annual Energy Policy Research Conference, 30(9), 37–41.
* Curtius, H. C., Hille, S. L., Berger, C., Hahnel, U. J. J., and Wüstenhagen, R. (2018). “Shotgun or snowball approach? Accelerating the diffusion of rooftop solar photovoltaics through peer effects and social norms.” Energy Policy, 118, 596–602.
* Dharshing, S. (2017). “Household dynamics of technology adoption: A spatial econometric analysis of residential solar photovoltaic (PV) systems in Germany.” Energy Research & Social Science, 23, 113–124.
* Duan, H., Zhang, G., Wang, S., and Fan, Y. (2018). “Peer interaction and learning: Cross-country diffusion of solar photovoltaic technology.” Journal of Business Research, 89, 57–66.
* Graziano, M., Fiaschetti, M., and Atkinson-Palombo, C. (2019). “Peer effects in the adoption of solar energy technologies in the United States: An urban case study.” Energy Research & Social Science, 48, 75–84.
* Heymann, F., Lopes, M., vom Scheidt, F., Silva, J. M., Duenas, P., Soares, F. J., and Miranda, V. (2019). “DER adopter analysis using spatial autocorrelation and information gain ratio under different census-data aggregation levels.” IET Renewable Power Generation.
* van der Kam, M. J., Meelen, A. A. H., van Sark, W. G. J. H. M., and Alkemade, F. (2018). “Diffusion of solar photovoltaic systems and electric vehicles among Dutch consumers: Implications for the energy transition.” Energy Research & Social Science, 46, 68–85.
* van der Kam, M., and van Sark, W. (2015). “Smart charging of electric vehicles with photovoltaic power and vehicle-to-grid technology in a microgrid; a case study.” Applied Energy, 152, 20–30.
* Litjens, G. B. M. A., Kausika, B. B., Worrell, E., and van Sark, W. G. J. H. M. (2018). “A spatio-temporal city-scale assessment of residential photovoltaic power integration scenarios.” Solar Energy, 174, 1185–1197.
* Lukanov, B. R., and Krieger, E. M. (2019). “Distributed solar and environmental justice: Exploring the demographic and socio-economic trends of residential PV adoption in California.” Energy Policy, 134, 110935.
* Mah, D. N., Wang, G., Lo, K., Leung, M. K. H., Hills, P., and Lo, A. Y. (2018). “Barriers and policy enablers for solar photovoltaics (PV) in cities: Perspectives of potential adopters in Hong Kong.” Renewable and Sustainable Energy Reviews, 92, 921–936.
* Martinopoulos, G., and Tsalikis, G. (2018). “Diffusion and adoption of solar energy conversion systems – The case of Greece.” Energy, 144, 800–807.
* Muchunku, C., Ulsrud, K., Palit, D., and Jonker‐Klunne, W. (2018). “Diffusion of solar PV in East Africa: What can be learned from private sector delivery models?” WIREs Energy and Environment, 7(3), e282.
* Nygaard, I., Hansen, U. E., Mackenzie, G., and Pedersen, M. B. (2017). “Measures for diffusion of solar PV in selected African countries.” International Journal of Sustainable Energy, 36(7), 707–721.
* Palm, A. (2016). “Local factors driving the diffusion of solar photovoltaics in Sweden: A case study of five municipalities in an early market.” Energy Research & Social Science, 14, 1–12.
* Palm, A. (2017). “Peer effects in residential solar photovoltaics adoption—A mixed methods study of Swedish users.” Energy Research & Social Science, 26, 1–10.
* Pless, J., Fell, H., and Sigrin, B. (2020). “Information Searching in the Residential Solar PV Market.” The Energy Journal, 41(4).
* Poruschi, L., and Ambrey, C. L. (2019). “Energy justice, the built environment, and solar photovoltaic (PV) energy transitions in urban Australia: A dynamic panel data analysis.” Energy Research & Social Science, 48, 22–32.
* “Powered By Faith, Religious Groups Emerge As A Conduit For A Just Solar Boom.” (n.d.). NPR.org, <https://www.npr.org/2019/12/15/784483810/powered-by-faith-religious-groups-emerge-as-a-conduit-for-a-just-solar-boom> (Dec. 16, 2019).
* Strupeit, L., and Palm, A. (2016). “Overcoming barriers to renewable energy diffusion: business models for customer-sited solar photovoltaics in Japan, Germany and the United States.” Journal of Cleaner Production, Advancing Sustainable Solutions: An Interdisciplinary and Collaborative Research Agenda, 123, 124–136.
* Wolske, K. S., Todd, A., Rossol, M., McCall, J., and Sigrin, B. (2018). “Accelerating demand for residential solar photovoltaics: Can simple framing strategies increase consumer interest?” Global Environmental Change, 53, 68–77.
* Wood, E. (2019). “Santa Barbara School District Looks at 18 Sites for Microgrids.” Microgrid Knowledge.



# Abstract 

The recent climate change has led to the development of various clean energy polices and technologies. As a result, the current rapid transition of energy systems due to the development, has the potential to significantly impact on how communities respond to any undesirable climate-related events. Furthermore, ‘energy divide’ (inequalities in access to energy services), could be the result of uneven distribution of the clean energy technologies. Empirical analyses of residential electric vehicle (EV) chargers in Seattle, WA, revealed that (1) there is a clustered pattern in the distribution of the EV charger installations, (2) housing stability and economic status explain the uneven distribution, and (3) some neighbors are more sensitive to the economic status and housing stability in terms of residential EV charger installations. The study results revealed social equity issues based on the uneven distribution, i.e., certain communities are underserved for the clean energy technologies. The study results will help policy makers to better support any underserved communities under limited resources (e.g., those who rent houses and have less finance for EV and charger) by devising equitable incentive distributions in response to clean energy technologies.

 
# Problem Statement

While a number of studies have investigated various aspects of the policies designed to support EV charger installations, there is still a dearth of studies aimed at investigating the impact of such policies on social equity. Two unanswered questions have emerged: (1) were there certain communities inadvertently left out from incentive opportunities? and (2) do those current policies help to encourage the social equity in clean energy technologies? To answer these questions, the present empirical study aimed to perform a spatial analysis of the distribution of EV charger installed-buildings in terms of housing and socioeconomic characteristics based on the census tracks of Seattle, WA. In particular, this study explored patterns of the residential (single family and multifamily) regarding EV charger by examining spatial clustering, associations among variables through several data sources. The examined data entails the socioeconomic and housing characteristics based on the American Community Survey of the census.

# Literature Review

Undesirable challenges and events such as natural disasters and climate change have triggered the development of sustainable and resilient energy infrastructures. Clean energy technologies, such as solar systems and electric vehicles, have been introduced and utilized all over the world seeking more reliable and sustainable energy systems in response to the climate change. In this regard, the uses of electric vehicles (EV) have rapidly increased in recent years with advancement of clean energy policies and associated incentives. 

## EV charging related policies 

EV charging infrastructure has a significant effect on EV adoption as one of the EV adoption challenges is range anxiety related to refueling/ recharging time, and the availability of refueling infrastructure in addition to higher price, and lack of education and awareness about EVs (Stumpf 2019). It is understood that charging opportunities should be ubiquitous, fast, and inexpensive in order to increase EV adoption. In order to encourage EV charger installation, some states established a new code requiring new multi-family construction to accommodate EV charger installation. For example, Washington State has a code WAC 51-50-0427: where parking is provided, at least 5 percent of parking spaces must have EV charging infrastructure (WA Legislature 2016). Furthermore, there are incentives to encourage adopting EVs and chargers. For example, tax exemptions are available for the labor and services rendered in respect to electric vehicle infrastructure (Revenue Washington State 2019). Moreover, as a way to encourage EV purchasing, a tax credit, ranging from $2,500 to $7,500, is offered by the federal (DOE 2019) while Washington State offer purchase and leasing tax exemptions, ranging from $2,600 to $3,100, on EVs (Banse 2018).


## Reliability of energy supply 

It is because reliability of energy supply has proven to be important especially during emergency situations when, for example, medical services are in high demand. Furthermore, about 1.1 billion people lack access to electricity and 52 billion USD annual investment is needed for the Sustainable Development Goals (SDGs) (IEA 2017). Lack of electricity affects more vulnerable people such as patients. Hurricane Maria caused additional deaths in Puerto Rico, especially to those who relied on respirators powered by electricity in 2017 (Robles et al. 2017). It is known that Maria incurred the longest blackout with more than 100 days in the US history (Irfan 2018). Respiratory patients are more vulnerable to power outages that mortality and respiratory hospital admissions increased significantly during the blackout (Lin et al. 2011). These studies and reports show that reliable power supply is essential to those vulnerable communities.

## Decentralized system 

To address climate change affecting people, it is necessary to have reliable energy services evenly distributed to all over the communities, particularly to those more vulnerable. Decentralized energy system is more reliable in terms of energy access and the low carbon challenges (Goldthau 2014). For example, micro-grids (decentralized energy system) at community level lead to more robust power systems (Wang and Reed 2017). Integration of interdependent infrastructures including, but not limited to energy, water, and telecommunication, also bring out the better mitigation in response to extreme weather (Zimmerman et al. 2017).


## Energy divide 

Clean energy technologies (e.g., solar panels and electric vehicles) have been introduced and utilized all over the world seeking more reliable and sustainable energy systems in response to climate change. For instance, solar panel installations have increased on residential, commercial buildings and utility-scale farms encouraged by clean energy policies and incentives such as federal tax credits. This rapid transition to the new energy system could lead to undesirable impacts on some communities as shown in the case of telecommunication where the digital divide has excluded vulnerable groups of people from knowledge-based societies and economies (Chen and Wellman 2004). If these deeply transformative changes in the power sector are not handled properly, an emerging electrical divide like the digital divide could appear (Caperton et al. 2013). In fact, European Union (EU) has already experienced that the uneven deployment of energy poverty and social distribution are correlated where spatial and social distribution is highly uneven (Bouzarovski and Tirado Herrero 2017). Committed leadership to implement a new policy in regard to the transition is required to avoid the uneven distribution of the power service.

## EV charging distribution 

Most charging occurs at home and 50% of EV users charge exclusively at home (Smart 2015). Accommodating home charging opportunities would contribute to EV adoption similar to the case of rooftop solar, where 49% of households are not able to install the solar system due to not owning the building, living in multi-family unit, and lack of roof space (Feldman 2015). In this context, it is necessary to review how residential charging infrastructures are spatially distributed to understand how clean energy policies and incentives have been implemented. This may identify an issue related to social equity; uneven distribution may indicate particular communities being left out of using clean energy technologies, particularly those more vulnerable to the climate change. 


Social justice was questioned in this context because the uneven distribution confirmed that there were certain communities left out from the clean energy technologies while decentralized energy systems such as residential solar are more reliable in response to climate change. Prudentialism ethics by reconciliation of the current efficient oriented policies and social equity, could approach the issue. Resilience was discussed by focusing on “preparation” and “availability” of energy systems. Vulnerability was explained in terms of energy dependency and situational conditions. Furthermore, desirable characteristics of resilient energy systems were identified as integrated energy system (IES) and distributed energy resources (DERs) featuring integrated energy diversity and decentralized energy systems. Finally, community solar could encourage the social equity by increasing participation of vulnerable communities in clean energy technologies or those, who were unable to host solar systems. It is because community solar satisfies both utilitarianism and social justice by taking advantage of two features - IES and DERs - while taking into account energy dependency in a situational conditions and preparatory resilience in favor of energy availability.


## Ethical concerns

The previous empirical analyses confirm that currently, there are communities left out from the benefit of one of clean energy technologies, residential solar. This raises an issue on social justice. From the utilitarian perspective, it is more efficient to use limited resources to maximize the global benefits thus, current distribution of residential solar as a result of the present clean energy policies, seems to get along with this ethical principle as opposed to the virtual ethic and social justice. In short, current clean energy policies or incentives are based on utilitarian ethics. For example, rebates, federal tax credits, performance payments, property tax exemptions, and sale tax exemptions are for those who are able to finance solar systems in addition to possessing their own houses. Opportunities to take part in the incentives are hard for those who can’t afford clean energy technologies.

To remedy the conflict of the two ethical principles - utilitarianism and social justice - reflective equilibrium needs to be constructed. There are two extremes, personal evaluation and ethical theory for the ethics in the built environment (Fox 2012). The reconciliation of the two extreme ends could be discussed in reflective equilibrium, which takes into account of the procedure of moving between the personal evaluation and the ethical theory. John Rawls (1972) introduced the concept of reflective equilibrium as a method to draw attention rather than applying it. The method of responsive cohesion could refer to reflective equilibrium such that the both sides are working or cling together through a process of adjustment, adaptation, and reconciling their different objectives and challenges. Responsive cohesion features reconciliation of personal evaluation and ethical theory as well. This is similar to the relationship between theory and observations in terms of epistemology and science, where both theory and observations are interdependent and systemically giving feedbacks each other to emerge in a form of dynamic change. Responsive Cohesion is a kind of relation between ‘things’ (objects, ideas, people, processes or systems) and other ‘things’ or contexts, in which cohesion is achieved by the way they respond to each other (Fox 2012).

Responsive cohesion, in this context, could be associated with prudentialism ethics by taking advantage of a process of reconciling the different objectives of the both extreme principles. Prudentialism is a moral principle in accordance with precaution to prevent a specific negative effect. Prudentialism also considers power dynamics from a pragmatic aspect. Prudentialism ethics could be, in part, called responsive cohesion because it features reconciliation of the extreme ends by avoiding the negative effects. Prudentialism can accommodate several ethical principles to seek the reconciliation of the different ethical principles.

The prudentialism ethics, thus, could address the issue by reconciling efficiency oriented policies and social equity viewpoints to avoid the particular negative effect, which is a uneven residential solar distribution or energy divide. It is, first, necessary to understand energy resilience in terms of vulnerability in response to climate change before discussing how to reconcile the two extreme objectives - an efficiency oriented goal and social equity.

## Resilience

Climate change and its impact on urban systems have raised questions of how to improve resilient systems especially the ones related to energy. Some of researchers introduced indexes related to resilience for analyses, and the others created mathematical functions to interpret the current phenomenon and simulated to prove their hypotheses. Energy resilience research is still at its emerging stage that a few literatures have tried to define energy resilience. First, the common definition of resilience could be discussed in terms of resilience abilities (preparation, absorption, recovery, and adaptation). It is also addressed in terms of sustainability related dimensions (availability, accessibility, affordability, and acceptability). “Preparation” in resilience ability and “availability” in sustainable dimension are considered to be the most critical to address energy resilience (Sharifi and Yamagata 2016). “Preparation” involves early adoption of planning and design measures to avoid potential disruptions. Preparation measure is known to be the most effective to improve the resilience. Furthermore, reserve margins, diverse energy sources, and monitoring systems could improve “availability” of energy services.

## Vulnerability

Vulnerability could be defined as being at risk of having limited capacity of power to protect one’s interest. Vulnerability is, however, mainly interpreted in connection with weakness, dependency, powerlessness, deficiency, and passivity. This implicit bias leads to a problem in ethical response as it entails negative connotation (Gilson 2013). Vulnerability could be interpreted in two sources - “inherent” and “situational” (Mackenzie 2013). Our neediness and dependence on others incur inherent vulnerability. This applies to energy dependency in the modern society because energy is essential to the basic human needs to sustain life. Situational vulnerability is context dependent such that negative impact of energy poverty on a certain community, would be different from the impact on other communities, depending upon social, political, economic, and environmental situations. For example, effects of a same hurricane would be less in a community, which has more resilient energy systems. Thus, it is necessary to discuss characteristics of resilient energy systems in terms of energy dependency and situational conditions (social, political, economic, and environmental).

## Characteristics for resilient energy systems

Community resilience could benefit from integrated energy diversity and decentralization in terms of reliable energy supply. Two emerging characteristics for energy resilience were presented: integrated energy system (IES) and distributed energy resources (DERs) (Lin and Bie 2016). IES is related to interdependency and diversity of systems while DERs represent several renewable energy sources spread across regions. DERs could be interpreted as decentralized energy systems such as micro-grids. When systems are combined, the complexity becomes characterized and the emergent behavior of the system is hard to be expected. In the study, two measures for energy resilience were introduced: hardware hardening and operational resilience strategies. Hardware hardening happens to be costly and influences only a limited part of the whole system that is less effective. On the other hand, increasing diversity of energy supply, would increase the system resilience.

### Integrated energy system (IES)

Understanding interdependencies of infrastructures are essential to address vulnerability. For instance, a study shows that interdependencies in infrastructures including energy, are important to a system resilience, and space and time are critical to assess hazard impact of interdependent lifeline infrastructures (Wang and Reed 2017). Furthermore, the study suggested that micro-grid at the community level, would increase robustness of the energy system in addition to hardening structure of power delivery components and increasing power generation redundancy. Robustness for power and telecommunication infrastructure was modeled in this study, in terms of resilience (Purple infra – human; Green infra – social, biological, hydrological, circulatory, and metabolic; Gray infra – lifelines; and modeling of interdependencies). Using state wide data, the study models the inoperability in terms of time (model parameters chosen by the goodness of fit). Time to recovery model estimates resource allocation pre-event. It found that peak wind speed and the corresponding parameters are not significant. Fragility models were developed by logistic regression. The same model for power was applied to telecommunication. Combined model (power and telecommunication) with the fragility model and single degree of freedom system (SDOF), may predict the restoration after hurricanes. Those models could be used to predict performance of the combined infrastructure systems in response to future storms. This study argues that social science involvement may be necessary to investigate from the community perspectives in addition to the infrastructure operators’ perspectives.

### Distributed energy resources (DERs)

Homogeneous and a sole energy production system not only adversely affects communities due to the lack of reliable energy supply, but also harms the social and environmental value of the built environment. Decentralization of energy production and supply has played an important role to resilient community as it is more robust in response to disruptions. For example, a study shows controllable and islandable micro-grid systems (decentralized systems) would improve the resiliency of power grids in extreme conditions (Shahidehpour et al. 2017). The study introduced 4 indexes - K: expected number of line on outage; LOLP: loss of load probability not being supplied; EDNS: expected demand not supplied; and G: difficulty level of grid recovery to promote the resilience improvement by introducing micro-grids to the power grid system. On the other hand, centralized energy production may have contributed to vulnerability of the current urban form as most of subsystems of human activities are relying on the sole energy production. The more dependent to a sole energy production, the more vulnerable a system would face interruptions.

Decentralized energy network, also, has enhanced the energy accessibility, and has been increasing due to efficient end-use appliance and low-cost photovoltaic supported by ICT (mobile phone) and virtual financial services (Alstone et al. 2015). There are still 1.3 billion people who currently lack access to electricity, and some barriers to mobilize the decentralized energy networks to local level. Governance of energy infrastructures in connection with polycentric governances will promote resilient energy systems (Goldthau 2014). It is because polycentric governances promote decentralized energy systems. Social science would be helpful to provide the reliable energy services as polycentric governance is critically related to socio-economic actors.

The investment of off-grid, one of the decentralized energy systems, however, features Unfavorable risk-return profiles and small investment volumes. Spatial diversity in a portfolio can reduce investment risks of private investments on resilient energy systems. Potential aggregation of small-scale renewable energy to investment is promising in that spatial diversification is helpful for derisking. Classification of risks, quantitative estimation of cost and derisking effects for aggregation of small-scale investments will help attracting private investment on off-grid. Barriers to private investment are financial, institutional and policy, and technical. Market risk could be decreased by portfolio with different geographies or industries. Systematic assessment is necessary for derisking related to regional disasters, policy change and regional industry (Malhotra et al. 2017).

## Community solar

A report from 2015 NREL estimates that about 50% of consumers and businesses are unable to host PV systems due to several reasons (e.g., not owning house, not enough finance, and not enough area to install rooftop solar) as confirmed by the previous empirical analyses in Seattle. By opening the market to these people, community solar or shared solar could represent 32%-49% of the distributed PV market in 2020, growing cumulative PV deployment in 2015-2020 by 5.5-11.0 GW and representing $8.2-$16.3 billion of cumulative investment (Feldman et al. 2015). Community solar models could work for those who can’t afford to install PV. Community solar (thanks to virtual net metering) is a purchasing arrangement in which multiple customers share the electricity or the economic benefits of solar power from a single array. An array is typically built in a single location, and individual customers sign up to own or lease parts of the array, or to purchase (or be credited for) some portion of the electricity generated by the array. Community solar may be located on public or jointly-owned property, and can be an easier way for customers to benefit from a local solar energy project.

Shared solar adoption should be considered in terms of political and economic barriers, which vary between states and program models. Those barriers are (1) occupants not owning the building, (2) lack of access to information, (3) difficulties with application submission, (4) stringent inspection requirements, (5) variation of solar incentives, (6) interconnection and net metering standards from state to state, (7) lack of regulatory clarity, and (8) lack of mandated or recommended guidance on program structure. Other barriers are the ownership as some community solar models only allow subscriptions while array owner could see a reduction in costs on the order of 50%. Securing available tax benefits is other barrier. Policy landscape depending on jurisdiction, will decide whether electricity costs will be credited to subscribers through net metering, or whether the utility will enter into a power purchase agreement (PPA) to purchase power directly from the energy producer (Augustine and McGavisk 2016). Furthermore, securities and Exchange Commission (SEC) requires for registration and disclosure of shared solar projects. SEC will regulate the projects depending on whether an interest in a shared solar project is a “security”, which may impact the way a shared solar program operates (Feldman et al. 2015).

Aggregation of community connections will reduce the barrier to grid-based service while designing local energy sharing community is unclear. A study analyzed several algorithms to find the optimal clustering of communities in terms of self-sufficiency, sharing cost, and stability (Yamagata et al. 2016). In the study, vehicle to community (V2C) was introduced with PV for energy generation and electric vehicle (EV) for energy storage where the energy is shared within the local community clustered. Trade-off between implementation and maintenance cost, and electricity self-sufficient was considered. This could be one of examples to design community for community based energy networks.

# Research Methodology

This study focuses on the City of Seattle open data portal which keeps the records of electrical permits issued between 2003 and 2018 in Seattle. Electrical permits are required when residential houses want to install EV chargers on their properties. The present study employed advanced data mining techniques to identify residential EV charger installation among the data sets. The data include geographical coordinates (latitudes and longitudes), dates of the EV charger installations, and EV charger contractors who installed the systems. Mapping the points of residential EV charger in the region allows to verify a certain pattern in the installations. The densities of the data points, normalized by the density of the total households shows a clustered pattern, where the value means scaled density value. 

Point patterns could be identified by G estimation which could be compared with complete spatial randomness (CSR). The G estimation function (EDF) of the nearest neighbor distances is defined as below, where di represents the distance from the i-th event to the nearest other event in A and n is the number of points. It simulated with 99 realizations under the null (resampling from n points) and formed the G estimate for each set, and produced Monte Carlo envelopes. The estimates being off the envelopes indicates the distribution of EV chargers is far from randomness. 

After point data was aggregated to the related census tracks, the data was examined in terms of the socioeconomic and housing characteristics based on the American Community Survey (ACS) of the census (2011 - 2015 ACS 5-Year estimates). The rate of the residential EV charger installations in each census track is the dependent variable in this study. Rest of variables are the proportions given census tracts.

The expected rate of residential EV charger per each census track is estimated based on the total number of housing units in Seattle and its residential EV charger numbers. Standardized Installation Ratio (SIR) is defined by the number of residential EV chargers over the expected number of residential EV chargers given the estimated proportion. In this context, SIR refers to the total number of residential EV charger over the total number of housing units in Seattle. The distribution of each census tract SIR shows a clustered pattern similar to that of the previous point data of residential EV chargers.

The residential EV charger rate is assumed to be associated with a Poisson count model considering its rare proportion with respect to the denominator (the total housing units) in a census track in addition to the fact that the number of residential EV chargers itself, is count data. The residuals, after fitting the Poisson model, show clustering with the similar pattern of SIR distribution across census tracks. This indicates that there is strong evidence of spatial dependency among the regions in Seattle.

A Moran’s I test identified global clustering in the distribution of the rates of residential EV charger with a very small p-value with the test statistic, 7.13. This confirms that the residential EV charger rate across census tracks is clustered. This clustering trend can be alleviated by fitting a model with appropriate covariates with the similar characteristics. For that, socioeconomic and housing characteristics were examined to identify the most proper covariates. Having verified that there is a spatial pattern in the residential EV charger rate, there might be related or shared factors in the socioeconomic and housing characteristics of the same region. It shows that housing, economy, and social inequality variables pairwise correlations.

Dimension reduction of covariates was performed by a factor analysis in consideration of avoiding multicollinearity. The newly generated factors were fitted to models to estimate the residential EV charger rates. Residuals were checked afterwards to see if there is still a clustered pattern. If there is still a clustered pattern, it means that the model does not address the spatial dependency. The factor analysis identifies the similar variables in terms of housing unit structures (single/multi-family house unit), housing ownership types (rent/owned), economic status (income levels and housing values), and inequality index. Housing unit structures show the similar trend of housing tenure while housing median value, high income class proportion, and household median incomes follow the similar pattern representing economic status. Residential EV charger rates and the factors from the dimension reduction show strong correlations. Generalized log-linear model (GLM) fits the data based on the factors, ML1, ML2 and ML3 without consideration of the spatial autocorrelation. Note that ML3, which was negatively correlated with the EV charger rates, becomes positively correlated after the model fit because predictors, ML1 and ML2 affected ML3 in the model. ML2 seems to be the most significant predictor with 0.43 estimated coefficient to the EV charger rate in Seattle. 

A Poisson lognormal spatial model, especially using BYM2 method, is tested to address any residual clustering issues using Bayesian method, Integrated Nested Laplace Approximations (INLA), which combines Laplace approximations and numerical integration in a very efficient manner. INLA enables Generalized Linear Mixed Models (GLMMs) addressing temporal and spatial error terms. An Intrinsic Conditional Auto-Regressive (ICAR) model addressed spatial autocorrelation. 

K-means clustering analysis, afterward, identifies similar regions in terms of socioeconomic and housing patterns in census tracks. It should be noted that K-means clustering does not take into account the EV charger rates for defining the Euclidean distance among data points, thus the clustered groups are determined only by the three predictors, ML1, ML2 and ML3. This will help to see the difference between the clustered groups and EV  charger rates.  Finally Geographically weighted regression (GWR) is used to address the local variation of coefficients of predictors by taking into account the local spatial dependency in order to locate regions more sensitive to each predictor.

# Contribution 

The climate change has led to development of clean energy polices, which has encouraged deployment of sustainable and resilient energy and transportation systems. Sustainable energy systems may mitigate climate change by reducing greenhouse gas emissions while resilient energy systems may improve the systems more robust in response to climate change. Energy divide, which might be a direct result of the rapid transition of energy systems, could affect the community resilience by uneven distribution of services. Empirical analyses were performed to verify the current status of distribution of one of the clean energy technologies, residential EV charger in Seattle. The results revealed that (1) there is a clustered pattern in the distribution of EV chargers, (2) housing stability and economic status explain the uneven distribution, and (3) there is area, where residential EV charger installations are more sensitive to the economic status and housing stability. The analyses questioned ethical issue of social equity.
The study results shows that EV charger infrastructures are concentrated on neighbors with higher housing ownership rates, higher single family housing rates, and higher income levels. These neighbors were categorized based on the housing and socio-economic characteristics to support policy makers to develop a policy that better help underserved communities under limited resources (e.g., those who rent multi-family houses and have less access to finance for EVs and chargers). Finally, the study identified the neighbors more sensitive to the particular characteristics expecting to help policy makers devise policies leading to equitable incentive distribution and access to clean energy technologies.

Self-sufficient energy system or decentralized energy production has increased the resilience of human societies and communities. So has done energy diversity, which is compared to the biological diversity keeping ecosystem healthy and stable. Diversification effect lessens the volatility or risk of investment by having less correlated assets in the package. Likewise, energy diversity, in the context of diverse energy sources, would reduce the risk of human society, thus enhance the stability of the built environment. Decentralized and diversified energy systems would enhance the community resilience in terms of vulnerability and resilience in response to climate change. After all, community solar would address the ethical judgement.



